sudo: required 
disc: bionic
language: java
jdk:
  - oraclejdk11
python:
  - "3.6"
services: docker
before_install:
  - sudo apt-get update
  - cd rest-with-spring-boot-udemy-aws-travis/RestWithSpringBootUdemy
  - echo "Let's start maven package!"
  - mvn clean package
  - cd ..
  - echo "We are in the docker folder!"
script:
  - echp "OK Were we GO!"
  - docker-compose build
before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin  
deploy:
  provider: script
  script:   
    docker tag rest-with-spring-boot-udemy:latest
    dinowork/rest-with-spring-boot-udemy:$TRAVIS_JOB_ID;
    docker push dinowork/rest-with-spring-boot-udemy;
  on:
    branch: master
after_success:
  - sudo apt-get -y install python3-pip python-dev
  - sudo pip3 install -U setuptools
  - sudo pip3 install -U virtualenvwrapper
  - python3 -V
  - pip3 -V
  - pip3 uninstall wheel
  - pip3 install wheel
  - pip3 install awscli --upgrade --user
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  - docker tag repo_udemy:latest $IMAGE_REPO_URL:$TRAVIS_JOB_ID
  - docker push 906539688966.dkr.ecr.us-east-2.amazonaws.com/repo_udemy:$TRAVIS_JOB_ID
  - add-apt-repository ppa:egenesan/app
  - apt-get update
  - apt-get install jq -y  
  - curl https://raw.githubusercontent.com/silinternational/ecs-deploy/master/ecs-deploy | sudo tee -a /usr/bin/ecs-deploy
  - sudo chmod +x /usr/bin/ecs-deploy
  - echo "AWS ECS-Deploy Setup is Configured"
  - ecs-deploy -c $CLUSTER_NAME -n $SERVICE_NAME -i $IMAGE_REPO_URL:$TRAVIS_JOB_ID -r $AWS_DEFAULT_REGION -t 240
notifications:
  email: false